improve code section
opendistro/for-elasticsearch-docs pull request #472
Opened 2021-04-16 18:40 UTC by inntran

*Description of changes:*
Default style from just-the-docs theme has a quite large line-height for code sections, and the font-family list only take macOS and Windows into consideration. On Linux ( RHEL 7 in my case ), Droid Sans Mono looks better.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-16 21:24 UTC, aetter requested changes
Hi @inntran, thanks a bunch for the PR. I'm completely in favor of adding more Linux-friendly fonts, and Droid Sans Mono is a good one.

I suspect we've hit an impasse on the line height, though. I think the current height helps out a lot with readability, especially on larger blocks like the Docker Compose file or response JSON, and it's very similar to the height that GitHub uses in its reviews.

2021-04-16 22:18 UTC, inntran commented
I checked on my Mac, yeah the 1.4 line-height looks fine. The font-family is more important than line-height on Linux. I'll update this PR.

2021-04-17 03:31 UTC, inntran commented
Before this explicit line-height specification, the code section would use inherited line-height from class "main-content", which is 1.6 in this case, that explains why the code section always looked weird to me.

2021-04-19 16:22 UTC, aetter commented
LGTM, thanks a bunch.

2021-04-19 16:22 UTC, merged